version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_index
    ports:
      - "908:80"
    volumes:
      - ./icloud-portfolio/dist:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
