version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "0907:80" # 对外暴露端口
    volumes:
      - ./icloud-portfolio/dist:/var/www/html
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:


