name: ci/cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 安装pnpm
      run: npm install -g pnpm

    - name: 安装依赖
      run: cd code && pnpm install

    - name: 构建
      run: cd code && pnpm run build

    - name: 连接服务器并部署
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/damesck/code
          git pull origin main
          /root/.nvm/versions/node/v22.15.0/bin/pnpm install
          /root/.nvm/versions/node/v22.15.0/bin/pnpm build
          cd ..
          docker-compose down
          docker-compose up -d --build
