name: ci/cd

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 安装pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: 安装 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
        cache-dependency-path: code/pnpm-lock.yaml

    - name: 安装依赖
      run: cd code && pnpm install --frozen-lockfile

    - name: 构建
      run: cd code && pnpm run build

    - name: 上传 dist 到服务器
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "code/dist/"
        target: "/root/damesck/code/dist_new"
        strip_components: 2

    - name: 替换 dist 并重启服务
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          rm -rf ~/damesck/code/dist_old
          [ -d ~/damesck/code/dist ] && mv ~/damesck/code/dist ~/damesck/code/dist_old
          mv ~/damesck/code/dist_new ~/damesck/code/dist
          rm -rf ~/damesck/code/dist_old
          cd ~/damesck
          docker compose up -d
